apiVersion: v2
name: nsi-node
description: Deploy a Network Service Interface node
type: application
version: 0.0.12

dependencies:
  - name: nsi-dds
    version: ">= 1.0.0"
    repository: "@nsi-node"
    condition: nsi-dds.enabled
  - name: nsi-pce
    version: "1.0.6"
    repository: "@nsi-node"
    condition: nsi-pce.enabled
  - name: nsi-safnari
    version: "1.0.7"
    repository: "@nsi-node"
    condition: nsi-safnari.enabled
  - name: nsi-envoy
    version: ">= 1.0.0"
    repository: "@nsi-node"
    condition: nsi-envoy.enabled
