apiVersion: v2
name: nsi-node
description: Deploy a Network Service Interface node
type: application
version: 0.1.20

dependencies:
  - name: nsi-dds
    version: "1.1.1"
    repository: "@nsi-node"
    condition: nsi-dds.enabled
  - name: nsi-pce
    version: "1.1.2"
    repository: "@nsi-node"
    condition: nsi-pce.enabled
  - name: nsi-safnari
    version: "1.1.6"
    repository: "@nsi-node"
    condition: nsi-safnari.enabled
  - name: nsi-envoy
    version: "1.2.0"
    repository: "@nsi-node"
    condition: nsi-envoy.enabled
  - name: nsi-opennsa
    version: "1.2.5"
    repository: "@nsi-node"
    condition: nsi-opennsa.enabled
  - name: nsi-requester
    version: "0.0.2"
    repository: "@nsi-node"
    condition: nsi-requester.enabled
  - name: supa
    version: "0.0.3"
    repository: "@nsi-node"
    condition: supa.enabled
  - name: polynsi
    version: "0.0.3"
    repository: "@nsi-node"
    condition: polynsi.enabled
  - name: postgresql
    version: "<11"
    repository: "@bitnami"
    condition: postgresql.enabled
