apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsi-pce.fullname" . }}
  labels:
    {{- include "nsi-pce.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.ports.name }}
      protocol: TCP
      name: http
  selector:
    {{- include "nsi-pce.selectorLabels" . | nindent 4 }}
