apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsi-safnari.fullname" . }}
  labels:
    {{- include "nsi-safnari.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.ports.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "nsi-safnari.selectorLabels" . | nindent 4 }}
