apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsi-dds.fullname" . }}
  labels:
    {{- include "nsi-dds.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
#  externalTrafficPolicy: Local
#  loadBalancerIP: {{ .Values.service.ipAddress }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.ports.name }}
      protocol: TCP
      name: http
  selector:
    {{- include "nsi-dds.selectorLabels" . | nindent 4 }}
